var snX;
var snY;
var mycanvas = document.getElementById('mycanvas');
var ctx = mycanvas.getContext('2d');
var snakeSize = 10; 
var w = 850;
var h = 850;
var score = 0;
var snake;
var snakeSize = 10;
var food;
var scores = document.getElementById('scores');
